version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_DB: myapp
      POSTGRES_PASSWORD: password
  web:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - ./:/locker_app
    stdin_open: true
    tty: true
