version: '3'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    volumes:
      # 初期データを投入するSQLが格納されているdir
      - ./db/mysql_init:/docker-entrypoint-initdb.d
      # 永続化するときにマウントするdir
      - ./db/mysql_data:/var/lib/mysql
    environment:
      # MYSQL_DATABASE: locker_app
      # MYSQL_USER: developper
      # MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
      TZ: 'Asia/Tokyo'
      # MYSQL_ALLOW_EMPTY_PASSWORD: true
    command: --default-authentication-plugin=mysql_native_password
  web:
    build:
      context: .
    ports:
      - 3000:3000
    depends_on:
      - db
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b 0.0.0.0"
    volumes:
      - ./:/locker_app
    stdin_open: true
    tty: true
